// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  features: dynamic(() => import("./Features")),
  hero: dynamic(() => import("./Hero")),
  image: dynamic(() => import("./Image")),
  image_cards: dynamic(() => import("./ImageCards")),
  navigation_item: dynamic(() => import("./NavigationItem")),
  photos_grid: dynamic(() => import("./PhotosGrid")),
  product_design: dynamic(() => import("./ProductDesign")),
  text: dynamic(() => import("./Text")),
};
