// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  image: dynamic(() => import("./Image")),
  image_cards: dynamic(() => import("./ImageCards")),
  navigation_item: dynamic(() => import("./NavigationItem")),
  text: dynamic(() => import("./Text")),
};
